name: Check New Posts

on:
  schedule:
    - cron: '*/10 * * * *'  # 10分ごとに実行される設定
  workflow_dispatch:  # 手動実行を可能にする設定
  
  concurrency:
  group: check-new-post
  cancel-in-progress: true  # 既存ジョブがあればキャンセル

jobs:
  check_posts:
    runs-on: ubuntu-latest  # GitHub Actionsの実行環境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # リポジトリのコードをチェックアウト

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'  # 使用するPythonのバージョン

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4  # 必要なライブラリをインストール

    - name: Run the notifier script
      run: python .github/workflows/notifier.py  # 作成した通知スクリプトを実行
