name: Check New Post

on:
  schedule:
    - cron: '*/10 * * * *'  # 10分ごとに実行
  workflow_dispatch:  # 手動実行を許可

concurrency:
  group: check-new-post
  cancel-in-progress: true  # 既存ジョブがあればキャンセル

jobs:
  check_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
        
      - name: Run Python script
        run: python .github/workflows/notifier.py
